language: node_js
node_js: node
before_install:
- rvm install 2.6.3
- gem install bundler
- npm install -g npm
install:
- bundle install
- npm install --prefix client
script:
- echo "Running tests..."
- bundle exec rspec
- npm run test --prefix client
deploy:
  provider: heroku
  api_key:
    secure: YcotoMSadk96aMmbLN3XhQDByjkBZ966rGat0TnM82U9PpczOB+bGGMngOi9FIi/SWYDDF+22MItsXPzvhWu/Q592syljnSGZxy5Is3XwGwSuStNyCwuSzXaadEFuLcMaJpGJd4zaU3EN4hQY4owYtJ3WmeYnqGO9lII1WLHDY5e7nYcXAS+akSN20XFTkD0encoUNWAzxi/1J8z90Y97hAoDR3pRl4v3qoX2ek2nkja/Dw4+ddqaRQ2l0DZJtvD7070ioOM6t2LViW4E/sDPtxQFj9jlsGmXsrXXQggVi2hcz1ADTs/MB2ZvgHV0N9gRLevuS5w/xIGXnH0/+iGKfNa/0JcNG7zMAuD5qKvaAONbNM6FfmF3ulgzGEheTTgr/0ybRb8ULdvy1otmWrkQ6tsuuZE/o/qdkO3zXWneTVy/jzx2nKuNj2rLNg7ffebV6GIrgJuQPCoXMNWxip3JzanVly6O/Mb9uRjzrvHDZ+QlNH6PBPrNDf02uX/Tk6WWhnXbobRKdpUNp+/9w+MPVBG1C3WJLaTJ+XxY3ZHsgNPTGwom/DGydmIXNODDHXa2wrEFmeoLq9TI+Z2bzvV4bTPtQnNIVUpOgPQmV7WA3n7+U8jb1sSrFkdkyr5a5eFmWAvTRnD0VINhuWvdWfaJ2oqeuPmUZOze7bJVUcdfZQ=
  app: support-engineer-spike-burton
  on:
    repo: spikeburton/support-engineer-salesloft-app
env:
  global:
    secure: NCacLEJtSafqN/MB2L5h6NjFvGctcwNwPI00qa+/b7WHTJSh77x1tZs7DBZqfz20+k1k70MOvxsOF7zUc1FRtnWizWL70/2PAPOBNJh12F7qjj6ndEv0D6rYhaXcoOHpvSrFj3VfKNZdXoj7Ne/70v1lqWm7HxqkRyBW+IjcmOG7RuSP9P3BhlRQhbllx+KRWVSZbF1TnaTF548GvEZ9py7qEQDaw64m0U/92BAqWrB/QsgAvPAhqzlKnKxBljYQlub4sPJAaHJ9Mk948w5jkRHjYHxgpl4S6xy8fZCYPzSGsiHrkV+t6XjtESlCdn2Yyjg5TRb4GfvSkJ3gTFqJgKTP8smLTQoJm5NibRHZ9N0NtZEvQ191xBfVUnzV88B/NKeIbDq7JBZ8xzu3NEynl2CBGko3FCUZ/Ui2KdUubQhbIWBeH9/IZuHddfZ4cVCiGyFNHHybDUmIj514IkL0IZW9bleZHMHGyaVQRdnFHnjyu7HnQewd4sb8Er+HF4ur1SZOxcPYg9g/+CIjThbO0doaXB4Eqpa8nGU06gLqFRHg7HELDWW6TPY4SHQ5ghXRcOEfIhq/Hzaxb+q08Om0GR2Rs+2bj3csaTt3wOSfstJHt97QpILnmDh7pypFSNKbZOxLJob94h4hZj3awjup90StUvEcBRDZpiWuqmtXD8s=
